name: xbatcher-ML-1-cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - numpy
  - xarray
  - intake
  - matplotlib
  - IPython
  - tensorflow
  - xbatcher
  - intake-xarray
  - gcsfs
#
# The balance of this environment file pins several libraries in order for
# to satisfy dependencies for the sphinx-pythia-theme 2022.3.22 package.
# 
  - sphinx==4.5.0
  - sphinxcontrib-applehelp<1.0.7 
  - sphinxcontrib-devhelp<1.0.5 
  - sphinxcontrib-htmlhelp<2.0.4 
  - sphinxcontrib-qthelp<1.0.6 
  - sphinxcontrib-serializinghtml<1.1.9
  - pydata-sphinx-theme<=0.8
  - jsonschema-with-format-nongpl<4.19.1
  - docutils==0.16
  - pip
  - pip:
      - sphinx-pythia-theme
