name: xbatcher-ML-1-cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server<2
  - pip
  - pip:
      - sphinx-pythia-theme
  - numpy
  - xarray
  - intake
  - matplotlib
  - IPython
  - tensorflow
  - xbatcher
